octopus:
  environments:
    - development
  development:
    shards:
      mumbai_shard:
        username: postgres
        password: ishaan
        host:     <%= ENV['IP'] %>
        adapter: postgresql
        database: mumbai_shard